name: ML Model CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch torchvision pytorch-lightning fastapi uvicorn pillow pytest wandb
        
    - name: Run tests
      run: |
        python -m pytest tests/

  train:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch torchvision pytorch-lightning fastapi uvicorn pillow wandb google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client
        
    - name: Configure Wandb
      env:
        WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
      run: |
        wandb login $WANDB_API_KEY
        
    - name: Setup dataset directory
      run: |
        mkdir -p dataset/
        mkdir -p dataset/cardboard/
        mkdir -p dataset/glass/
        mkdir -p dataset/metal/
        mkdir -p dataset/paper/
        mkdir -p dataset/plastic/
        mkdir -p dataset/trash/
        
    - name: Download dataset from Google Drive
      run: |
        gdown --folder ${{ secrets.DATASET_FOLDER_ID }} -O dataset
        
    - name: Train model
      env:
        WANDB_PROJECT: trash-classification
      run: |
        python train.py

    - name: Upload model to Google Drive
      env:
        GOOGLE_DRIVE_CREDENTIALS: ${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}
        GOOGLE_DRIVE_FOLDER_ID: ${{ secrets.GOOGLE_DRIVE_MODEL_FOLDER_ID }}
      run: |
        python upload_to_drive.py