name: ML Model CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch torchvision pytorch-lightning fastapi uvicorn pillow pytest
        
    - name: Run tests
      run: |
        python -m pytest tests/

  train:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch torchvision pytorch-lightning fastapi uvicorn pillow
        
    - name: Train model
      run: |
        python train.py
        
    - name: Upload model artifact
      uses: actions/upload-artifact@v3
      with:
        name: model-weights
        path: Trash-Classification.ckpt

  deploy:
    needs: train
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Download model weights
      uses: actions/download-artifact@v3
      with:
        name: model-weights
        
    - name: Deploy to cloud (example for Azure)
      env:
        AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      run: |
        # Add your deployment commands here
        echo "Deploying to cloud..."