name: ML Model CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch torchvision pytorch-lightning fastapi uvicorn pillow wandb google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client gdown
        
    - name: Setup dataset directory
      run: |
        mkdir -p dataset
        
    - name: Download and verify dataset
      run: |
        # Download dataset
        gdown https://drive.google.com/drive/folders/${{ secrets.DATASET_FOLDER_ID }} --folder -O dataset --remaining-ok
        
        # Debug information
        echo "=== Dataset Structure ==="
        ls -la dataset/
        echo "=== Detailed Structure ==="
        find dataset/ -type d
        echo "=== File Count per Class ==="
        for dir in dataset/*/; do
          echo "$dir: $(ls -1 "$dir" 2>/dev/null | wc -l) files"
        done
        
    - name: Configure Wandb
      env:
        WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
      run: |
        wandb login $WANDB_API_KEY
        
    - name: Train model
      env:
        WANDB_PROJECT: trash-classification
      run: |
        python train.py